# Generated by Django 5.2.5 on 2025-08-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель техники')),
                ('serial_number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Зав. № машины')),
                ('engine_model', models.CharField(blank=True, max_length=100, verbose_name='Модель двигателя')),
                ('engine_serial', models.CharField(blank=True, max_length=100, verbose_name='Зав. № двигателя')),
                ('transmission_model', models.CharField(blank=True, max_length=150, verbose_name='Модель трансмиссии')),
                ('transmission_serial', models.CharField(blank=True, max_length=100, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_model', models.CharField(blank=True, max_length=100, verbose_name='Модель ведущего моста')),
                ('drive_axle_serial', models.CharField(blank=True, max_length=100, verbose_name='Зав. № ведущего моста')),
                ('steer_axle_model', models.CharField(blank=True, max_length=100, verbose_name='Модель управляемого моста')),
                ('steer_axle_serial', models.CharField(blank=True, max_length=100, verbose_name='Зав. № управляемого моста')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('buyer', models.CharField(blank=True, max_length=255, verbose_name='Покупатель (организация)')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес поставки')),
                ('options', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('service_company', models.CharField(blank=True, max_length=255, verbose_name='Сервисная компания')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(blank=True, null=True, verbose_name='Дата отказа')),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, м/час')),
                ('failure_node', models.CharField(blank=True, max_length=255, verbose_name='Узел отказа')),
                ('failure_description', models.TextField(blank=True, verbose_name='Описание отказа')),
                ('recovery_method', models.TextField(blank=True, verbose_name='Способ восстановления')),
                ('used_spare', models.TextField(blank=True, null=True, verbose_name='Использованные запчасти')),
                ('restored_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время простоя (часов)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.machine', verbose_name='Зав. № машины')),
            ],
            options={
                'ordering': ['-failure_date', 'machine__serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100, verbose_name='Вид ТО')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведения ТО')),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('service_company', models.CharField(blank=True, max_length=255, verbose_name='Организация, проводившая ТО')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.machine', verbose_name='Зав. № машины')),
            ],
            options={
                'ordering': ['-date', 'machine__serial_number'],
            },
        ),
    ]
