# Generated by Django 5.2.5 on 2025-08-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-failure_date', 'machine__serial_number'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['serial_number'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date', 'machine__serial_number'], 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.maintenancetype', verbose_name='Вид ТО'),
        ),
    ]
