# Generated by Django 5.2.5 on 2025-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_machine_client_machine_service_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.IntegerField(unique=True, verbose_name='Зав. № машины'),
        ),
    ]
