# Generated by Django 5.2.5 on 2025-09-05 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='Только цифры')], verbose_name='Зав. № машины'),
        ),
    ]
